export const SECURITY_POLICY = {
    directives: {
        connectSrc: [
            "'self' blob: data:",
            '*.gov.uk',
            'dc.services.visualstudio.com',
            '*.launchdarkly.com',
            'https://*.google-analytics.com',
            'https://*.googletagmanager.com',
            'https://*.analytics.google.com',
            '*.hmcts.net',
            'wss://*.webpubsub.azure.com',
            'wss://em-icp-webpubsub.aat.platform.hmcts.net',
            'wss://em-icp-webpubsub.demo.platform.hmcts.net',
            'wss://em-icp-webpubsub.perftest.platform.hmcts.net',
            'wss://em-icp-webpubsub.ithc.platform.hmcts.net',
            'wss://em-icp-webpubsub.prod.platform.hmcts.net',
            'wss://em-icp-webpubsub.platform.hmcts.net',
            'https://*.in.applicationinsights.azure.com',
            'https://*.monitor.azure.com',
        ],
        defaultSrc: ["'self'"],
        fontSrc: ["'self'", 'https://fonts.gstatic.com', 'data:'],
        formAction: ["'none'"],
        frameAncestors: ["'self'"],
        frameSrc: ["'self'"],
        imgSrc: [
            "'self'",
            'data:',
            'https://*.google-analytics.com',
            'https://*.googletagmanager.com',
            'https://raw.githubusercontent.com/hmcts/',
            'https://stats.g.doubleclick.net/',
            'https://ssl.gstatic.com/',
            'https://www.gstatic.com/',
            'https://fonts.gstatic.com',
        ],
        mediaSrc: ["'self'"],
        scriptSrc: [
            "'self'",
            "'unsafe-eval'",
            'https://*.google-analytics.com',
            'https://*.googletagmanager.com',
            'az416426.vo.msecnd.net',
        ],
        styleSrc: [
            "'self'",
            'https://fonts.googleapis.com',
            'https://fonts.gstatic.com',
            'https://www.googletagmanager.com',
            "'unsafe-hashes'",
            "'sha256-edW+KixhylnxLGOJoo3iC5UsjEj4HijvIQvP3cgo7ig='",
            "'sha256-47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU='",
            "'sha256-DJfMaqJPUQ8dcrB4BNp7Hk9x/6AmRHJoHeHJSUMqzeA='",
            "'sha256-PUpjPYGfAmEqPFbJgzytzwXvem4pAO4/Vn4vY9N/9mo='",
            "'sha256-NaWUtA8E+t7IhPoHjsBpWJhZof7wB1NowAAs7OFVhtk='",
            "'sha256-mEKHMA+CDqhMsFO42kojAVphmL8B/+8kOs+xLnhmpKI='",
            "'sha256-de03O04uUKqPga/XPvKIlAl/486c63YCqBx+hCtXzkk='",
            "'sha256-mZIpVsrsRHtS8BDymn5RFYGtUWMJcGXO1vvXeMevx2Q='",
            "'sha256-TFxvKBiu7bBOpDs5WGvlGnU4PuzJ4vRkPE0rcK0hrgY='",
            "'sha256-wzwmHJlxHXpjoeCzhtZN8MSlKu4MwzKqrxFa5yRwSOc='",
            "'sha256-h2y2do65nZkX2gfZczVMi/gSnkwaL9nMs2zq96ptnuo='",
            "'sha256-T5nj9jFODjjGLqCU0CqLF/43Z8XGJ2L848bS/zP4ZMQ='",
            "'sha256-Kv06yB5ibmZ3z5o95fVCCGai/YDt70jki+VELkixwy8='",
            "'sha256-mCa+j4qDe1YusNTvVk1b128nobVBKioXEmiFBZ0Mi5M='",
            "'sha256-AOlHbM/aK6U3JvaI54fui8mQHry8aXfK31AjhD031TI='",
            "'sha256-jhkllhYxS5VhnRgK3JXkNQkZ8ce4+ZzzQTrN/h/HW/Q='",
            "'sha256-PXPLZjBtIF1QnRYD2almOOTJxM6Qbs597VedYAKA4YU='",
        ],
    },
}

export const getContentSecurityPolicy = (helmet: any) => {
    return helmet.contentSecurityPolicy({
        directives: {
            ...SECURITY_POLICY.directives,
            scriptSrc: [...SECURITY_POLICY.directives.scriptSrc, (req: any, res: any) => `'nonce-${res.locals.nonce}'`],
        },
    })
}
