on:
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request. 
  # push:
  #   branches:
  #     - master
  pull_request:
      types: [opened, synchronize, reopened]
name: PR Build
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn install
      - run: yarn ci
      - run: yarn test
      - run: yarn test:coverage
      - name: Setup SonarCloud
        uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
