on:
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request. 
  # push:
  #   branches:
  #     - master
  pull_request:
      types: [opened, synchronize, reopened]
name: PR Build
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v2
      - name: Setup Node & Generate report
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn install
      - run: yarn ci
      - run: yarn test
      - run: yarn test:coverage
      - run: sed -i 's+/home/runner/work/rpx-xui-node-lib/rpx-xui-node-lib+/github/workspace+g' coverage/lcov.info
      - name: Archive code coverage results
        uses: actions/upload-artifact@v1
        with:
          name: code-coverage-report
          path: coverage 

  sonarcloud:
    needs: build
    name: SonarCloud Trigger
    runs-on: ubuntu-latest
    steps:
    - name: Clone Repo
      uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - name: Download code coverage results
      uses: actions/download-artifact@v1
      with:
        name: code-coverage-report
        path: coverage
    - name: Analyze with SonarCloud
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}